# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cardUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(302, 394)
        Form.setMinimumSize(QtCore.QSize(302, 394))
        Form.setMaximumSize(QtCore.QSize(302, 423))
        Form.setStyleSheet("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 301, 391))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.image.setMinimumSize(QtCore.QSize(230, 230))
        self.image.setMaximumSize(QtCore.QSize(200, 200))
        self.image.setBaseSize(QtCore.QSize(50, 50))
        self.image.setAutoFillBackground(True)
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.verticalLayout.addWidget(self.image, 0, QtCore.Qt.AlignHCenter)
        self.word_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.word_label.setMinimumSize(QtCore.QSize(299, 94))
        self.word_label.setMaximumSize(QtCore.QSize(299, 94))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.word_label.setFont(font)
        self.word_label.setStyleSheet("font: 30pt \"Helvetica\";")
        self.word_label.setAlignment(QtCore.Qt.AlignCenter)
        self.word_label.setObjectName("word_label")
        self.verticalLayout.addWidget(self.word_label)
        self.trans = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trans.setFont(font)
        self.trans.setStyleSheet("font: 24pt \".AppleSystemUIFont\";")
        self.trans.setText("")
        self.trans.setObjectName("trans")
        self.verticalLayout.addWidget(self.trans, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.word_label.setText(_translate("Form", "Textel"))
