# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changePassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 189)
        Dialog.setMinimumSize(QtCore.QSize(480, 189))
        Dialog.setMaximumSize(QtCore.QSize(480, 189))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 441, 153))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Al Nile")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 20pt \"Al Nile\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Al Nile")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 20pt \"Al Nile\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.login_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.login_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.login_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.login_edit.setStyleSheet("color: rgb(0, 0, 0); border-radius: 10px;")
        self.login_edit.setObjectName("login_edit")
        self.gridLayout.addWidget(self.login_edit, 1, 1, 1, 1)
        self.new_password_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.new_password_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.new_password_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.new_password_edit.setStyleSheet("color: rgb(0, 0, 0); border-radius: 10px;")
        self.new_password_edit.setObjectName("new_password_edit")
        self.gridLayout.addWidget(self.new_password_edit, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.error_label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.error_label.setStyleSheet("font: 16pt \"Al Nile\";")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 15px;\n"
"background-color: rgb(255, 255, 255)")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Новый пароль:"))
        self.label.setText(_translate("Dialog", "Введите login:"))
