# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editSet.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 667)
        Dialog.setMinimumSize(QtCore.QSize(541, 592))
        Dialog.setMaximumSize(QtCore.QSize(9999, 9999))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.head_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.head_label.setStyleSheet("font: 24pt \"Helvetica\";")
        self.head_label.setObjectName("head_label")
        self.verticalLayout.addWidget(self.head_label)
        self.all_cards = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.all_cards.setWidgetResizable(True)
        self.all_cards.setObjectName("all_cards")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 559, 521))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.all_cards.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.all_cards)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.choose_all_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.choose_all_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 19px;\n"
"background-color: rgb(255, 255, 255);\n"
"height: 18px;\n"
"\n"
"")
        self.choose_all_button.setObjectName("choose_all_button")
        self.horizontalLayout_2.addWidget(self.choose_all_button)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.delete_set_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.delete_set_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 19px;\n"
"background-color: rgb(255, 255, 255);\n"
"height: 18px;\n"
"\n"
"")
        self.delete_set_button.setObjectName("delete_set_button")
        self.horizontalLayout_2.addWidget(self.delete_set_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_editions_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.save_editions_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 19px;\n"
"background-color: rgb(255, 255, 255);\n"
"height: 20px;\n"
"\n"
"")
        self.save_editions_button.setObjectName("save_editions_button")
        self.horizontalLayout.addWidget(self.save_editions_button)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 15px;\n"
"background-color: rgb(255, 255, 255)")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.head_label.setText(_translate("Dialog", "редактирование"))
        self.choose_all_button.setText(_translate("Dialog", "Выбрать все"))
        self.delete_set_button.setText(_translate("Dialog", "Удалить сет"))
        self.save_editions_button.setText(_translate("Dialog", "Сохранить изменения"))
