# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameWithCards.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(573, 553)
        Dialog.setMinimumSize(QtCore.QSize(570, 0))
        Dialog.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 571, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.set_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.set_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.set_label.setStyleSheet("font: 25pt \"Al Nile\";")
        self.set_label.setObjectName("set_label")
        self.verticalLayout.addWidget(self.set_label)
        self.hor = QtWidgets.QHBoxLayout()
        self.hor.setObjectName("hor")
        self.verticalLayout.addLayout(self.hor)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setStyleSheet("font: 18pt \"Al Nile\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.word = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.word.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 18px;\n"
"background-color: rgb(254, 252, 255);\n"
"border-radius: 30px;\n"
"height: 30px;")
        self.word.setObjectName("word")
        self.horizontalLayout.addWidget(self.word)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.check_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.check_button.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 19px;\n"
"background-color: rgb(254, 252, 255);\n"
"border-radius: 30px;\n"
"height: 30px;")
        self.check_button.setObjectName("check_button")
        self.horizontalLayout.addWidget(self.check_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.right_or_not = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.right_or_not.setMinimumSize(QtCore.QSize(0, 20))
        self.right_or_not.setMaximumSize(QtCore.QSize(16777215, 40))
        self.right_or_not.setStyleSheet("")
        self.right_or_not.setText("")
        self.right_or_not.setObjectName("right_or_not")
        self.verticalLayout.addWidget(self.right_or_not)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 16px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.set_label.setText(_translate("Dialog", "Заучиваем сет"))
        self.label_2.setText(_translate("Dialog", "Введите перевод:"))
        self.check_button.setText(_translate("Dialog", "Проверить"))
