# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 257)
        Dialog.setMinimumSize(QtCore.QSize(504, 257))
        Dialog.setMaximumSize(QtCore.QSize(504, 257))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 481, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Al Nile")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 18pt \"Al Nile\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Al Nile")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 18pt \"Al Nile\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Al Nile")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 18pt \"Al Nile\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_password = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.new_password.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 19px;\n"
"background-color: rgb(255, 255, 255);\n"
"height: 16px;\n"
"\n"
"")
        self.new_password.setObjectName("new_password")
        self.horizontalLayout.addWidget(self.new_password)
        self.create_new_ak = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.create_new_ak.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 19px;\n"
"background-color: rgb(255, 255, 255);\n"
"height: 16px;\n"
"\n"
"")
        self.create_new_ak.setObjectName("create_new_ak")
        self.horizontalLayout.addWidget(self.create_new_ak)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.login = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.login.setMinimumSize(QtCore.QSize(0, 25))
        self.login.setMaximumSize(QtCore.QSize(16777215, 25))
        self.login.setStyleSheet("color: rgb(0, 0, 0); border-radius: 10px;")
        self.login.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.login.setObjectName("login")
        self.gridLayout.addWidget(self.login, 0, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.password.setMinimumSize(QtCore.QSize(25, 0))
        self.password.setMaximumSize(QtCore.QSize(16777215, 25))
        self.password.setStyleSheet("color: rgb(0, 0, 0); border-radius: 10px;")
        self.password.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.error_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.error_label.setStyleSheet("font: 16pt \"Al Nile\";")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.close_or_not = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.close_or_not.setFont(font)
        self.close_or_not.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.close_or_not.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 15px;\n"
"background-color: rgb(255, 255, 255)")
        self.close_or_not.setOrientation(QtCore.Qt.Horizontal)
        self.close_or_not.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.close_or_not.setObjectName("close_or_not")
        self.verticalLayout.addWidget(self.close_or_not, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Dialog)
        self.close_or_not.accepted.connect(Dialog.accept)
        self.close_or_not.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Логин"))
        self.label_2.setText(_translate("Dialog", "Пароль"))
        self.label_3.setText(_translate("Dialog", "Забыли пароль?"))
        self.new_password.setText(_translate("Dialog", "Сменить пароль"))
        self.create_new_ak.setText(_translate("Dialog", "Регистрация"))
