# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 547)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(485, 547))
        MainWindow.setMaximumSize(QtCore.QSize(485, 547))
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, -10, 471, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quet = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.quet.setStyleSheet("background-color: rgb(145, 255, 240);\n"
"border-radius: 10px;\n"
"height: 40px;\n"
"font: 20pt \"Al Nile\";\n"
"")
        self.quet.setObjectName("quet")
        self.horizontalLayout.addWidget(self.quet)
        self.login_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.login_button.setStyleSheet("background-color: rgb(145, 255, 240);\n"
"border-radius: 10px;\n"
"height: 40px;\n"
"font: 20pt \"Al Nile\";\n"
"")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout.addWidget(self.login_button)
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name_label.setStyleSheet("font: 16pt \"Al Nile\";")
        self.name_label.setObjectName("name_label")
        self.horizontalLayout.addWidget(self.name_label, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(5999, 420))
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color:rgb(114, 81, 114)\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 461, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 20pt \".AppleSystemUIFont\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.layout_sets = QtWidgets.QVBoxLayout()
        self.layout_sets.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.layout_sets.setObjectName("layout_sets")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_2)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 363))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.layout_sets.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.layout_sets)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 471, 401))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.delete_cards = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_cards.sizePolicy().hasHeightForWidth())
        self.delete_cards.setSizePolicy(sizePolicy)
        self.delete_cards.setMinimumSize(QtCore.QSize(360, 0))
        self.delete_cards.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.delete_cards.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 250, 255);\n"
"border-radius: 20px;\n"
"height: 40px;\n"
"font: 18pt \"Al Nile\";")
        self.delete_cards.setObjectName("delete_cards")
        self.verticalLayout_3.addWidget(self.delete_cards, 0, QtCore.Qt.AlignHCenter)
        self.edit_set = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_set.sizePolicy().hasHeightForWidth())
        self.edit_set.setSizePolicy(sizePolicy)
        self.edit_set.setMinimumSize(QtCore.QSize(360, 0))
        self.edit_set.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.edit_set.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 250, 255);\n"
"border-radius: 20px;\n"
"height: 40px;\n"
"font: 18pt \"Al Nile\";")
        self.edit_set.setObjectName("edit_set")
        self.verticalLayout_3.addWidget(self.edit_set, 0, QtCore.Qt.AlignHCenter)
        self.show_all = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.show_all.sizePolicy().hasHeightForWidth())
        self.show_all.setSizePolicy(sizePolicy)
        self.show_all.setMinimumSize(QtCore.QSize(360, 0))
        self.show_all.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.show_all.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 250, 255);\n"
"border-radius: 20px;\n"
"height: 40px;\n"
"font: 18pt \"Al Nile\";")

        self.show_all.setObjectName("show_all")
        self.verticalLayout_3.addWidget(self.show_all, 0, QtCore.Qt.AlignHCenter)
        self.new_card = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_card.sizePolicy().hasHeightForWidth())
        self.new_card.setSizePolicy(sizePolicy)
        self.new_card.setMinimumSize(QtCore.QSize(360, 0))
        self.new_card.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.new_card.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 250, 255);\n"
"border-radius: 20px;\n"
"height: 40px;\n"
"font: 18pt \"Al Nile\";")
        self.new_card.setObjectName("new_card")
        self.verticalLayout_3.addWidget(self.new_card, 0, QtCore.Qt.AlignHCenter)
        self.create_new_set = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_new_set.sizePolicy().hasHeightForWidth())
        self.create_new_set.setSizePolicy(sizePolicy)
        self.create_new_set.setMinimumSize(QtCore.QSize(360, 0))
        self.create_new_set.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.create_new_set.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 250, 255);\n"
"border-radius: 20px;\n"
"height: 40px;\n"
"font: 18pt \"Al Nile\";")
        self.create_new_set.setObjectName("create_new_set")
        self.verticalLayout_3.addWidget(self.create_new_set, 0, QtCore.Qt.AlignHCenter)

        self.game_with_words = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.game_with_words.sizePolicy().hasHeightForWidth())
        self.game_with_words.setSizePolicy(sizePolicy)
        self.game_with_words.setMinimumSize(QtCore.QSize(360, 0))
        self.game_with_words.setMaximumSize(QtCore.QSize(9999, 16777215))
        self.game_with_words.setStyleSheet("background-color: rgb(0, 0, 0);\n"
                                          "color: rgb(255, 250, 255);\n"
                                          "border-radius: 20px;\n"
                                          "height: 40px;\n"
                                          "font: 18pt \"Al Nile\";")
        self.game_with_words.setObjectName("game_with_words")
        self.verticalLayout_3.addWidget(self.game_with_words, 0, QtCore.Qt.AlignHCenter)


        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 485, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.quet.setText(_translate("MainWindow", "Выход"))
        self.login_button.setText(_translate("MainWindow", "Вход"))
        self.name_label.setText(_translate("MainWindow", "Неизвестный"))
        self.label.setText(_translate("MainWindow", "Выберите набор для заучивания"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Запоминаем слова"))
        self.delete_cards.setText(_translate("MainWindow", "Удаление карточек"))
        self.edit_set.setText(_translate("MainWindow", "Редактировать набор"))
        self.show_all.setText(_translate("MainWindow", "Посмотреть все картчоки"))
        self.new_card.setText(_translate("MainWindow", "Создать карточку"))
        self.create_new_set.setText(_translate("MainWindow", "Сделать новый набор из карточек"))
        self.game_with_words.setText(_translate("MainWindow", "Задания по английскому"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Главная"))
