# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showAllCards.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 544)
        Dialog.setMinimumSize(QtCore.QSize(504, 544))
        Dialog.setMaximumSize(QtCore.QSize(504, 544))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.all_cards = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.all_cards.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.all_cards.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.all_cards.setWidgetResizable(True)
        self.all_cards.setObjectName("all_cards")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 459, 449))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.all_cards.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.all_cards)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"font-size: 15px;\n"
"background-color: rgb(255, 255, 255)")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
